### ISSUE TITLE
setdebugmode.sh not working?

### ISSUE THREAD

**Issue by kevincannon** [davidderaedt/CC-EXT-SDK#5]
Downloaded this, but it's not working. It there a dependency not mentioned in the docs, or does this still work?

./setdebugmode.sh 
Add: ":PlayerDebugMode" Entry Already Exists
kill: 24633: Operation not permitted
kill: 24637: Operation not permitted
kill: 40503: No such process

**Comment by davidderaedt** [comment]
Those errors are expected in some cases, and do not invalidate the debugging mode. The first one tells you that the entry was already there (probably because you tried several times and it had worked since the 1st time). 
FYI the kill command is meant to force the system take the entry into account asap, without having to reboot. 
I suggest you restart your system and launch your extension, which should now work as expected.
